### ISSUE TITLE
Fails for support.sectigo.com

### ISSUE THREAD

**Issue by marcelstoer** [OPEnSLab-OSU/bearssl-certificate-utility#76]
Sending a request for "support.sectigo.com" through the app in the browser fails with HTTP 502 and a CORS error.

> Reason: CORS header ‘Access-Control-Allow-Origin’ missing

Doing so with HTTPie reveals this:

```
❯ http -v https://certutil.prototypical.pro/getheader\?domain\=support.sectigo.com\&array_name\=TAs\&length_name\=TAs_NUM\&guard_name\=CERTIFICATES
GET /getheader?domain=support.sectigo.com&array_name=TAs&length_name=TAs_NUM&guard_name=CERTIFICATES HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: certutil.prototypical.pro
User-Agent: HTTPie/3.0.2



HTTP/1.1 502 Bad Gateway
Connection: keep-alive
Content-Length: 36
Content-Type: application/json
Date: Mon, 28 Mar 2022 19:09:33 GMT
x-amz-apigw-id: PtYtFG8RvHcFv4Q=
x-amzn-ErrorType: InternalServerErrorException
x-amzn-RequestId: ccca48f1-f97d-4e07-8cb9-f04d58ff2bd1

{
    "message": "Internal server error"
}
```

**Comment by marcelstoer** [comment]
I realize the bug likely is in the code deployed at certutil.prototypical.pro but I wasn't able to find any source for it. Wanted to see if I could provide a fix.

**Comment by prototypicalpro** [comment]
The code for that API is available [here](https://github.com/prototypicalpro/LambdaWorkspace/tree/master/getcertificate). I did some troubleshooting and was able to narrow down the problem to the root certificate bundle ([certifi](https://pypi.org/project/certifi/)) not containing the root or intermediate certificates needed to verify the [weird chain that sectigo uses](https://www.ssllabs.com/ssltest/analyze.html?d=support.sectigo.com). This problem isn't isolated to sectigo and also occurs for www.amazon.com. 

To fix this issue I'll probably have the script pull root certificates from `/etc/ssl/certs` instead of certifi, but that code is so old it'll take me a minute to dust it off. If you'd to take a look at it feel free.
